# Build a cuisine recommender

In [25]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score,precision_score,confusion_matrix,classification_report
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType

data = pd.read_csv('../data/cleaned_cuisines_own.csv')
data.head()

X = data.drop(["Unnamed: 0", "cuisine"], axis=1)
X.head()

,almond,angelica,anise,anise_seed,apple,apple_brandy,apricot,armagnac,artemisia,artichoke,...,whiskey,white_bread,white_wine,whole_grain_wheat_flour,wine,wood,yam,yeast,yogurt,zucchini
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [26]:
y = data[["cuisine"]]
y.head()

  cuisine
0  indian
1  indian
2  indian
3  indian
4  indian

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

model = SVC(kernel="linear", C=10, probability=True, random_state=0)
model.fit(X_train, np.ravel(y_train))

SVC(C=10, kernel='linear', probability=True, random_state=0)

In [28]:
y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

     chinese       0.72      0.69      0.71       259
      indian       0.91      0.87      0.89       226
    japanese       0.77      0.79      0.78       234
      korean       0.84      0.74      0.79       246
        thai       0.75      0.87      0.80       234

    accuracy                           0.79      1199
   macro avg       0.80      0.79      0.79      1199
weighted avg       0.79      0.79      0.79      1199

In [29]:
initial_type = [('float_input', FloatTensorType([None, 380]))]
options = {id(model): {'nocl': True, 'zipmap': False}}